/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poundstogallons;

import javax.swing.GroupLayout.Group;
import javax.swing.ImageIcon;
import javax.swing.JTextField;

/**
 *
 * @author D Garcia
 */
public class UI_Main extends javax.swing.JFrame {

    /**
     * Creates new form UI_Main
     */
    public UI_Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TF_pounds = new javax.swing.JTextField();
        JL_gallons = new javax.swing.JLabel();
        JL_enterPounds = new javax.swing.JLabel();
        JL_gallonsOut = new javax.swing.JLabel();
        JB_clearButton = new javax.swing.JButton();
        JL_backGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pounds to Gallons");
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(0, 0, 0));
        setIconImage(new ImageIcon(PoundsToGallons.class.getResource("images/ES icon.png")).getImage());
        setResizable(false);

        jPanel1.setOpaque(false);

        TF_pounds.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        TF_pounds.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TF_pounds.setToolTipText("Enter pounds");
        TF_pounds.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        TF_pounds.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TF_poundsCaretUpdate(evt);
            }
        });
        TF_pounds.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TF_poundsKeyTyped(evt);
            }
        });

        JL_gallons.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        JL_gallons.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JL_gallons.setText("Gallons:");

        JL_enterPounds.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        JL_enterPounds.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JL_enterPounds.setText("Enter Pounds");

        JL_gallonsOut.setBackground(new java.awt.Color(0, 0, 0));
        JL_gallonsOut.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        JL_gallonsOut.setForeground(new java.awt.Color(255, 0, 0));
        JL_gallonsOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JL_gallonsOut.setText("0.0");
        JL_gallonsOut.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(153, 153, 153), new java.awt.Color(102, 102, 102), new java.awt.Color(153, 153, 153), new java.awt.Color(102, 102, 102)));
        JL_gallonsOut.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JL_gallonsOut.setFocusable(false);
        JL_gallonsOut.setOpaque(true);

        JB_clearButton.setFont(new java.awt.Font("Courier New", 0, 36)); // NOI18N
        JB_clearButton.setText("CLEAR");
        JB_clearButton.setMaximumSize(new java.awt.Dimension(131, 37));
        JB_clearButton.setMinimumSize(new java.awt.Dimension(131, 37));
        JB_clearButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JB_clearButtonMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(JL_gallons)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JL_gallonsOut, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JL_enterPounds, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(JB_clearButton, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                                .addComponent(TF_pounds)))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JL_enterPounds)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TF_pounds, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JB_clearButton, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_gallonsOut)
                    .addComponent(JL_gallons, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        JL_backGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poundstogallons/images/rock_texture2.jpg"))); // NOI18N
        JL_backGround.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        JL_backGround.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/poundstogallons/images/rock_texture2.jpg"))); // NOI18N
        JL_backGround.setFocusable(false);
        JL_backGround.setPreferredSize(new java.awt.Dimension(420, 248));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(JL_backGround, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 446, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(JL_backGround, javax.swing.GroupLayout.PREFERRED_SIZE, 276, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    /**
     * Checks input for leading zeros when a key is typed
     * @param evt 
     */
    private void TF_poundsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TF_poundsKeyTyped
        JTextField x = (JTextField)evt.getSource();
        String text = x.getText();
        int carretPosition = TF_pounds.getCaretPosition();

        // Check input for leading zeros
        if(text.length() >= 7 
                || evt.getKeyChar() > '9' 
                || evt.getKeyChar() < '0' 
                || (evt.getKeyChar() == '0' && carretPosition < 1 )
                ) 
            evt.consume(); // Consume (ignore) key stroke if true
    }//GEN-LAST:event_TF_poundsKeyTyped
    
    
    
    final double FACTOR = 8.34; // 1 pound of water is approximately 8.34 gallons.
    /**
     * Does calculations of gallons when caret position is updated (numbers entered).
     * @param evt 
     */
    private void TF_poundsCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TF_poundsCaretUpdate
        JTextField x = (JTextField)evt.getSource();
        String s = "0.0";
        
        try {
            String text = x.getText();                  // get input area
            double input = Double.parseDouble(text);    // convert text to double
            double conversion = input / FACTOR;         // calculate gallons
            s = Double.toString(conversion);            // convert calculation to string
            s = s.substring(0, s.indexOf(".") + 2);     // set gallons text area
            
        } catch (Exception e) { 
            s = "0.0";
        }
        finally{
            JL_gallonsOut.setText(s);
        }
    }//GEN-LAST:event_TF_poundsCaretUpdate

    
    /**
     * This listener clears the input area if the clear button is clicked.
     * @param evt 
     */
    private void JB_clearButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_clearButtonMousePressed
        TF_pounds.setText(null);
    }//GEN-LAST:event_JB_clearButtonMousePressed
    
    
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_clearButton;
    private javax.swing.JLabel JL_backGround;
    private javax.swing.JLabel JL_enterPounds;
    private javax.swing.JLabel JL_gallons;
    private javax.swing.JLabel JL_gallonsOut;
    private javax.swing.JTextField TF_pounds;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
